# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'
plugin 'cocoapods-patch'

target 'test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'QKMRZScanner'
end